CREATE TABLE tb_produtos (id BIGINT AUTO_INCREMENT, titulo VARCHAR(255) NOT NULL,
autor VARCHAR(255) NOT NULL, editora VARCHAR(255) NOT NULL, assunto VARCHAR(255) NOT NULL,
preco DECIMAL(6,2), PRIMARY KEY(id));

SELECT * FROM tb_produtos;