CREATE TABLE tb_alunos (id BIGINT AUTO_INCREMENT, aluno VARCHAR(255) NOT NULL, idade INT,
serie VARCHAR(255), disciplina VARCHAR(255) NOT NULL, nota DECIMAL(6,2), PRIMARY KEY(id));

SELECT * FROM tb_alunos;